# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d768634130c4a844a28e6462dd3b6313bcd2e273d1ff112c8fd9206d4115377cc45f904dbfba2720dfe800c489798c1496a9a11c6bff126c021eeb25c88c697e

test:
  secret_key_base: bcd4f56401b03ab5f583c509c8c5b6765df9b6b714278d896d081d2c0d92613f64c442c98318a512c920b4eff275297435ad4dd19a4df9218dd0dfdf5d269bc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
